####################################
#=== UPYAY - CONFIGURATION FILE ===#
####################################


################################
#=== LANGUAGE CONFIGURATION ===#
################################
#
# Write the sentence in your language 
# System is up to date (default: "there is nothing to do")
NOTHING_TO_DO_STRING="there is nothing to do"
# Startup notification (default: "...starting upyay...")
STARTUP_STRING="Let's gooo!!!"
# System update error (default: "Error during system update!")
UPDATE_ERROR_STRING="La mise à jour a planté.."
# System update successful (default: "System update successful")
UPDATE_SUCCESS_STRING="Ca a marché !"
# AUR mirrors list update error (default: "Error during AUR mirrors list update !")
AUR_MIRRORS_ERROR_STRING="Erreur pendant la mise à jour des mirroirs AUR !"
# EOS mirrors list update error (default: "Error during EOS mirrors list update !")
EOS_MIRRORS_ERROR_STRING="Erreur pendant la mise à jour des mirroirs EOS !"
# Mirrors lists successfully updated (default: "Lists update successful !")
LISTS_SUCCESS_STRING="Lists mises à jour !"
# Journal cleanup error (default: "Error during journal cleanup !")
JOURNAL_ERROR_STRING="Le nettoyage des journaux systemd a planté !"
# Journal cleanup successful (default: "Journal cleanup successful")
JOURNAL_SUCCESS_STRING="Nettoyage des journaux réussi"
# Cache cleanup error (default: "Error during cache cleanup !")
CACHE_ERROR_STRING="Le nettoyage du cache a planté !"
# Cache cleanup successful (default: "Cache cleanup successful")
CACHE_SUCCESS_STRING="Nettoyage du cache réussi"
# No orphan packages have been found (default: "No orphan packages !")
NO_ORPHANS_STRING="Pas de paquets orphelins"
# Orphan packages removed successfully (default: "Orphans remove successful !")
ORPHANS_SUCCESS_STRING="Suppression des paquets orphelins réussie"





####################################
#=== NOTIFICATION CONFIGURATION ===#
####################################
#
# The duration of the notification display (default: 10000)
NOTIFICATION_TIMEOUT=10000
# The notification icons
# Success (default: "object-select-symbolic")
ICON_SUCCESS="object-select-symbolic"
# Error (default: "dialog-error-symbolic")
ICON_ERROR="dialog-error-symbolic"
# Success (default: "dialog-information-symbolic")
ICON_INFO="dialog-information-symbolic"

################################
#=== FEATURES CONFIGURATION ===#
################################
#
# Enable automatic backup filesaving (default: false)
AUTO_BACKUP=false
# Enable automatic updated packages filesaving (default: false)
AUTO_SAVE_UPDATED=false
# Specify the oldest journalctl logs you want to keep (default: 4weeks)
VACCUUM_TIME=4weeks

####################
#=== OS OPTIONS ===#
####################
#
# If you're running EndeavourOS, you can also update
# the EOS specific mirrors list. (default: false)
ENDEAVOUROS_OPTION=false