####################################
#=== UPYAY - CONFIGURATION FILE ===#
####################################


################################
#=== LANGUAGE CONFIGURATION ===#
################################
#
# Write the sentence in your language (default: "there is nothing to do")
NOTHING_TO_DO_STRING="there is nothing to do"


####################################
#=== NOTIFICATION CONFIGURATION ===#
####################################
#
# The duration of the notification display (default: 10000)
NOTIFICATION_TIMEOUT=10000
# The notification icons
# Success (default: "object-select-symbolic")
ICON_SUCCESS="object-select-symbolic"
# Error (default: "dialog-error-symbolic")
ICON_ERROR="dialog-error-symbolic"
# Success (default: "dialog-information-symbolic")
ICON_INFO="dialog-information-symbolic"

################################
#=== FEATURES CONFIGURATION ===#
################################
#
# Enable automatic backup filesaving (default: false)
AUTO_BACKUP=false
# Enable automatic updated packages filesaving (default: false)
AUTO_SAVE_UPDATED=false
# Specify the oldest journalctl logs you want to keep (default: 4weeks)
VACCUUM_TIME=4weeks

####################
#=== OS OPTIONS ===#
####################
#
# If you're running EndeavourOS, you can also update
# the EOS specific mirrors list. (default: false)
ENDEAVOUROS_OPTION=false